name: Issue & PR assignment

on:
  issues:
    types: [opened]
  #pull_request:
  #  types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: dschach
          numOfAssignee: 1
          allowSelfAssign: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
